language: cpp
compiler:
  - gcc

before_install:
  # We need this line to have g++4.8 available in apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  # We want to compile with g++ 4.8 when rather than the default g++
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - python script/cpplint_dir.py

script: ./build/ci_build.sh

notifications:
  email: false

after_success: ./build/ci_run_test.sh
